name: Jira Create and Update Issue
description: Create a new Jira issue
branding:
  icon: "check-square"
  color: "blue"
inputs:
  project:
    description: Key of the project
    required: true
  issuetype:
    description: "Type of the issue to be created. Example: 'Incident'"
    required: true
  summary:
    description: Issue summary
    required: true
  newIssue:
    description: Create new issue
    required: false
    default: "false"
  comment:
    description: Comment
    required: false
  description:
    description: Issue description
    required: false
  labels:
    description: Issue labels
    required: false
  attachments:
    description: Issue attachments and separate by commar, example ./report.json,./lerna.json
    required: false
  fields:
    description: Additional fields in JSON format
    required: false
outputs:
  issue:
    description: Key of the newly created issue
runs:
  using: "node16"
  main: "./dist/index.js"
